In [1]:
from joblib import dump, load
import numpy as np
model_3 = load('RE.joblib') 
features = np.array([[-0.43803561, -0.48816033, -1.03122246, -0.26761547, -0.38849153,
       -0.59044659,  0.014193  , -0.50420611, -0.52206387, -0.67560744,
       -0.88075763,  0.41171531, -0.42841599]])
model_3.predict(features)

array([22.06])

In [2]:
from joblib import dump, load
import numpy as np
model_3 = load('RE.joblib') 
features = np.array([[-0.43974299, -0.48816033,  2.07938386, -0.26761547,  0.218856  ,
       -0.38796944,  0.55793172, -0.74521334, -0.86744673, -1.31612945,
        0.28298544,  0.2462144 ,  0.21279566]])
model_3.predict(features)

array([20.554])

In [3]:
from joblib import dump, load
import numpy as np
model_3 = load('RE.joblib') 
features = np.array([[ 0.71161886, -0.48816033,  0.99211174, -0.26761547,  1.17692535,
        0.26414661,  1.07695505, -0.97055152,  1.66536094,  1.51877351,
        0.79503239,  0.39841993,  0.60749398]])
model_3.predict(features)

array([13.317])